import fs from "fs";
import path from "path";
import { themeManifestSchema, type ThemeManifest } from "../src/core/lib/theme-manifest-schema";

const THEMES_DIR = path.join(process.cwd(), "src/themes");
const REGISTRY_OUT = path.join(process.cwd(), "src/core/generated/theme-registry.ts");
const TOKENS_OUT = path.join(process.cwd(), "src/core/generated/theme-tokens.css");

function loadThemes(): Record<string, ThemeManifest> {
    if (!fs.existsSync(THEMES_DIR)) return {};
    const themes: Record<string, ThemeManifest> = {};
    for (const dir of fs.readdirSync(THEMES_DIR, { withFileTypes: true })) {
        if (!dir.isDirectory()) continue;
        const manifestPath = path.join(THEMES_DIR, dir.name, "theme.json");
        if (!fs.existsSync(manifestPath)) continue;
        let raw: unknown;
        try {
            raw = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
        } catch (e) {
            console.error(`[themes] ${dir.name}: invalid JSON —`, (e as Error).message);
            continue;
        }
        const parsed = themeManifestSchema.safeParse(raw);
        if (!parsed.success) {
            const first = parsed.error.issues[0];
            console.error(`[themes] ${dir.name}: schema invalid at ${first.path.join(".")} — ${first.message}`);
            continue;
        }
        if (parsed.data.id !== dir.name) {
            console.error(`[themes] ${dir.name}: manifest id "${parsed.data.id}" doesn't match directory name`);
            continue;
        }
        themes[dir.name] = parsed.data;
    }
    return themes;
}

function emitTokensCss(themes: Record<string, ThemeManifest>): string {
    const blocks: string[] = [
        "/* Auto-generated by scripts/generate-theme-registry.ts — do not edit. */",
        "",
    ];
    for (const [id, theme] of Object.entries(themes)) {
        for (const [modeName, modeDef] of Object.entries(theme.modes.available)) {
            const lines: string[] = [];

            const colorDefaults = new Map<string, string>();
            for (const [name, def] of Object.entries(theme.tokens?.colors ?? {})) {
                if (def.default) colorDefaults.set(name, def.default);
            }
            for (const [name, value] of Object.entries(modeDef.tokens?.colors ?? {})) {
                colorDefaults.set(name, value);
            }
            for (const [name, value] of colorDefaults) lines.push(`    --uxw-color-${name}: ${value};`);

            const fontDefaults = new Map<string, string>();
            for (const [name, def] of Object.entries(theme.tokens?.fonts ?? {})) {
                if (def.default) fontDefaults.set(name, def.default);
            }
            for (const [name, value] of Object.entries(modeDef.tokens?.fonts ?? {})) {
                fontDefaults.set(name, value);
            }
            for (const [name, value] of fontDefaults) lines.push(`    --uxw-font-${name}: ${value};`);

            if (theme.tokens?.radius && "default" in theme.tokens.radius && theme.tokens.radius.default !== undefined) {
                lines.push(`    --uxw-radius: ${theme.tokens.radius.default};`);
            }

            blocks.push(`[data-theme="${id}"][data-mode="${modeName}"] {`);
            blocks.push(...lines);
            blocks.push("}");
            blocks.push("");
        }
    }
    return blocks.join("\n");
}

function emitRegistryTs(themes: Record<string, ThemeManifest>): string {
    const merged: Record<string, ThemeManifest> = {};
    for (const [id, raw] of Object.entries(themes)) {
        merged[id] = raw;
    }
    const ids = Object.keys(merged);
    const defaultId = ids.includes("flat") ? "flat" : (ids[0] ?? "flat");
    const lines: string[] = [
        "// Auto-generated by scripts/generate-theme-registry.ts — do not edit.",
        "import type { ThemeManifest } from '@/core/lib/theme-manifest-schema';",
        "",
        `export const themeRegistry: Record<string, ThemeManifest> = ${JSON.stringify(merged, null, 2)} as Record<string, ThemeManifest>;`,
        "",
        `export const themeIds = ${JSON.stringify(ids)} as const;`,
        "",
        `export const defaultThemeId = ${JSON.stringify(defaultId)};`,
        "",
    ];
    return lines.join("\n");
}

const COMPONENTS_OUT = path.join(process.cwd(), "src/core/generated/theme-components.tsx");

function emitComponentsTsx(themes: Record<string, ThemeManifest>): string {
    const imports: string[] = [];
    const entries: string[] = [];
    let counter = 0;

    for (const [themeId, theme] of Object.entries(themes)) {
        if (!theme.components) continue;
        const fields: string[] = [];
        for (const [name, rel] of Object.entries(theme.components)) {
            const varName = `Override_${counter++}`;
            imports.push(`const ${varName} = dynamic(() => import("@/themes/${themeId}/${rel.replace(/\.(tsx|ts|jsx|js)$/, "")}"));`);
            fields.push(`    ${JSON.stringify(name)}: ${varName},`);
        }
        entries.push(`  ${JSON.stringify(themeId)}: {\n${fields.join("\n")}\n  },`);
    }

    return [
        "// Auto-generated by scripts/generate-theme-registry.ts — do not edit.",
        "import dynamic from 'next/dynamic';",
        "import type { ComponentType } from 'react';",
        "",
        ...imports,
        "",
        "export const themeComponents: Record<string, Record<string, ComponentType>> = {",
        ...entries,
        "};",
        "",
        "export function getThemeComponent(themeId: string, name: string): ComponentType | null {",
        "  return themeComponents[themeId]?.[name] ?? null;",
        "}",
        "",
    ].join("\n");
}

const ADMIN_ROUTES_OUT = path.join(process.cwd(), "src/core/generated/theme-admin-routes.ts");

interface ThemeAdminNavItem {
    path: string;
    label: string;
    icon?: string;
    kind: "settings" | "custom";
    group?: string;
}

function emitAdminRoutesTs(themes: Record<string, ThemeManifest>): string {
    const map: Record<string, ThemeAdminNavItem[]> = {};
    for (const [themeId, theme] of Object.entries(themes)) {
        const items: ThemeAdminNavItem[] = [];
        for (const [group, def] of Object.entries(theme.settings ?? {})) {
            items.push({
                path: `/theme/${group}`,
                label: def.label,
                icon: def.icon,
                kind: "settings",
                group,
            });
        }
        for (const route of theme.adminRoutes ?? []) {
            items.push({ path: route.path, label: route.path, kind: "custom" });
        }
        if (items.length > 0) map[themeId] = items;
    }
    return [
        "// Auto-generated by scripts/generate-theme-registry.ts — do not edit.",
        "export interface ThemeAdminNavItem {",
        "  path: string;",
        "  label: string;",
        "  icon?: string;",
        "  kind: 'settings' | 'custom';",
        "  group?: string;",
        "}",
        "",
        `export const themeAdminRoutes: Record<string, ThemeAdminNavItem[]> = ${JSON.stringify(map, null, 2)};`,
        "",
    ].join("\n");
}

function run(): void {
    const themes = loadThemes();
    fs.mkdirSync(path.dirname(REGISTRY_OUT), { recursive: true });
    fs.writeFileSync(REGISTRY_OUT, emitRegistryTs(themes));
    fs.writeFileSync(TOKENS_OUT, emitTokensCss(themes));
    fs.writeFileSync(COMPONENTS_OUT, emitComponentsTsx(themes));
    fs.writeFileSync(ADMIN_ROUTES_OUT, emitAdminRoutesTs(themes));
    console.log(`Generated theme registry (${Object.keys(themes).length} themes).`);
}

run();
