import fs from "fs";
import path from "path";
import { themeManifestSchema, type ThemeManifest } from "../src/core/lib/theme-manifest-schema";

const THEMES_DIR = path.join(process.cwd(), "src/themes");
const REGISTRY_OUT = path.join(process.cwd(), "src/core/generated/theme-registry.ts");
const TOKENS_OUT = path.join(process.cwd(), "src/core/generated/theme-tokens.css");

function loadThemes(): Record<string, ThemeManifest> {
    if (!fs.existsSync(THEMES_DIR)) return {};
    const themes: Record<string, ThemeManifest> = {};
    for (const dir of fs.readdirSync(THEMES_DIR, { withFileTypes: true })) {
        if (!dir.isDirectory()) continue;
        const manifestPath = path.join(THEMES_DIR, dir.name, "theme.json");
        if (!fs.existsSync(manifestPath)) continue;
        let raw: unknown;
        try {
            raw = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
        } catch (e) {
            console.error(`[themes] ${dir.name}: invalid JSON —`, (e as Error).message);
            continue;
        }
        const parsed = themeManifestSchema.safeParse(raw);
        if (!parsed.success) {
            const first = parsed.error.issues[0];
            console.error(`[themes] ${dir.name}: schema invalid at ${first.path.join(".")} — ${first.message}`);
            continue;
        }
        if (parsed.data.id !== dir.name) {
            console.error(`[themes] ${dir.name}: manifest id "${parsed.data.id}" doesn't match directory name`);
            continue;
        }
        themes[dir.name] = parsed.data;
    }
    return themes;
}

function emitTokensCss(themes: Record<string, ThemeManifest>): string {
    const blocks: string[] = [
        "/* Auto-generated by scripts/generate-theme-registry.ts — do not edit. */",
        "",
    ];
    for (const [id, theme] of Object.entries(themes)) {
        for (const [modeName, modeDef] of Object.entries(theme.modes.available)) {
            const lines: string[] = [];

            const colorDefaults = new Map<string, string>();
            for (const [name, def] of Object.entries(theme.tokens?.colors ?? {})) {
                if (def.default) colorDefaults.set(name, def.default);
            }
            for (const [name, value] of Object.entries(modeDef.tokens?.colors ?? {})) {
                colorDefaults.set(name, value);
            }
            for (const [name, value] of colorDefaults) lines.push(`    --uxw-color-${name}: ${value};`);

            const fontDefaults = new Map<string, string>();
            for (const [name, def] of Object.entries(theme.tokens?.fonts ?? {})) {
                if (def.default) fontDefaults.set(name, def.default);
            }
            for (const [name, value] of Object.entries(modeDef.tokens?.fonts ?? {})) {
                fontDefaults.set(name, value);
            }
            for (const [name, value] of fontDefaults) lines.push(`    --uxw-font-${name}: ${value};`);

            if (theme.tokens?.radius && "default" in theme.tokens.radius && theme.tokens.radius.default !== undefined) {
                lines.push(`    --uxw-radius: ${theme.tokens.radius.default};`);
            }

            blocks.push(`[data-theme="${id}"][data-mode="${modeName}"] {`);
            blocks.push(...lines);
            blocks.push("}");
            blocks.push("");
        }
    }
    return blocks.join("\n");
}

function emitRegistryTs(themes: Record<string, ThemeManifest>): string {
    const merged: Record<string, ThemeManifest> = {};
    for (const [id, raw] of Object.entries(themes)) {
        merged[id] = raw;
    }
    const ids = Object.keys(merged);
    const defaultId = ids.includes("flat") ? "flat" : (ids[0] ?? "flat");
    const lines: string[] = [
        "// Auto-generated by scripts/generate-theme-registry.ts — do not edit.",
        "import type { ThemeManifest } from '@/core/lib/theme-manifest-schema';",
        "",
        `export const themeRegistry: Record<string, ThemeManifest> = ${JSON.stringify(merged, null, 2)} as Record<string, ThemeManifest>;`,
        "",
        `export const themeIds = ${JSON.stringify(ids)} as const;`,
        "",
        `export const defaultThemeId = ${JSON.stringify(defaultId)};`,
        "",
    ];
    return lines.join("\n");
}

function run(): void {
    const themes = loadThemes();
    fs.mkdirSync(path.dirname(REGISTRY_OUT), { recursive: true });
    fs.writeFileSync(REGISTRY_OUT, emitRegistryTs(themes));
    fs.writeFileSync(TOKENS_OUT, emitTokensCss(themes));
    console.log(`Generated theme registry (${Object.keys(themes).length} themes).`);
}

run();
