
import fs from 'fs';
import path from 'path';

const THEMES_DIR = path.join(process.cwd(), 'src/themes');
const OUTPUT_FILE = path.join(process.cwd(), 'src/core/generated/theme-registry.tsx');

async function generate() {
    console.log('🎨 Generating theme registry...');

    if (!fs.existsSync(THEMES_DIR)) {
        console.warn('⚠️ No themes directory found at src/themes');
        return;
    }

    const themes = fs.readdirSync(THEMES_DIR).filter(file => {
        return fs.statSync(path.join(THEMES_DIR, file)).isDirectory();
    });

    const imports: string[] = [];
    const themeEntries: string[] = [];

    themes.forEach(themeId => {
        const themeDir = path.join(THEMES_DIR, themeId);
        const configFile = path.join(themeDir, 'theme.config.ts');

        if (fs.existsSync(configFile)) {
            // Import config
            imports.push(`import { ${themeId}Theme as ${themeId}Config } from "@/themes/${themeId}/theme.config";`);

            // Check for components
            const componentsDir = path.join(themeDir, 'components');
            let componentMap = '{}';

            if (fs.existsSync(componentsDir)) {
                const componentFiles = fs.readdirSync(componentsDir)
                    .filter(f => f.endsWith('.tsx') || f.endsWith('.ts'));

                if (componentFiles.length > 0) {
                    const compImports: string[] = [];
                    componentFiles.forEach(compFile => {
                        const compName = path.basename(compFile, path.extname(compFile));
                        const importName = `${themeId}_${compName}`;
                        imports.push(`import ${importName} from "@/themes/${themeId}/components/${compName}";`);
                        compImports.push(`${compName}: ${importName}`);
                    });
                    componentMap = `{ ${compImports.join(', ')} }`;
                }
            }

            themeEntries.push(`
  "${themeId}": {
    config: ${themeId}Config,
    components: ${componentMap}
  }`);
        }
    });

    const content = `// @ts-nocheck
// This file is auto-generated by scripts/generate-themes.ts
// Do not edit this file manually.

import { Theme } from "@/core/types/theme";
${imports.join('\n')}

export const themeRegistry: Record<string, Theme> = {
${themeEntries.join(',\n')}
};

export const defaultThemeId = "flat";
`;

    // Ensure output dir exists
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(OUTPUT_FILE, content);
    console.log(`✅ Generated registry for ${themes.length} themes.`);
}

generate().catch(console.error);
