
import fs from 'fs';
import path from 'path';

const THEMES_DIR = path.join(process.cwd(), 'src/themes');
const OUTPUT_FILE = path.join(process.cwd(), 'src/core/generated/theme-registry.tsx');

async function generate() {
    console.log('Generating theme registry...');

    if (!fs.existsSync(THEMES_DIR)) {
        console.warn('No themes directory found at src/themes');
        return;
    }

    const themes = fs.readdirSync(THEMES_DIR).filter(file => {
        return fs.statSync(path.join(THEMES_DIR, file)).isDirectory();
    });

    const imports: string[] = [];
    const themeEntries: string[] = [];

    // Convert theme id to a valid JS identifier (camelCase)
    const toIdentifier = (s: string) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

    themes.forEach(themeId => {
        const themeDir = path.join(THEMES_DIR, themeId);
        const configFile = path.join(themeDir, 'theme.config.ts');

        if (fs.existsSync(configFile)) {
            const ident = toIdentifier(themeId);

            // Import config
            imports.push(`import { ${ident}Theme as ${ident}Config } from "@/themes/${themeId}/theme.config";`);

            // Check for components
            const componentsDir = path.join(themeDir, 'components');
            let componentMap = '{}';

            if (fs.existsSync(componentsDir)) {
                const componentFiles = fs.readdirSync(componentsDir)
                    .filter(f => f.endsWith('.tsx') || f.endsWith('.ts'));

                if (componentFiles.length > 0) {
                    const compImports: string[] = [];
                    componentFiles.forEach(compFile => {
                        const compName = path.basename(compFile, path.extname(compFile));
                        const importName = `${ident}_${compName}`;
                        imports.push(`import ${importName} from "@/themes/${themeId}/components/${compName}";`);
                        compImports.push(`${compName}: ${importName}`);
                    });
                    componentMap = `{ ${compImports.join(', ')} }`;
                }
            }

            themeEntries.push(`
  "${themeId}": {
    config: ${ident}Config,
    components: ${componentMap}
  }`);
        }
    });

    const content = `// eslint-disable
// This file is auto-generated by scripts/generate-themes.ts
// Do not edit this file manually.

import { Theme, ThemeConfig } from "@/core/types/theme";
${imports.join('\n')}

const rawRegistry: Record<string, Theme> = {
${themeEntries.join(',\n')}
};

/**
 * Resolve theme inheritance.
 * If a theme has \`extends: "parentId"\`, recursively merge the parent's
 * config and components into the child, with the child overriding.
 * Detects cycles via a visited set.
 */
function resolveTheme(id: string, visited: Set<string> = new Set()): Theme {
    if (visited.has(id)) {
        throw new Error(\`Theme inheritance cycle detected at \${id}\`);
    }
    visited.add(id);

    const theme = rawRegistry[id];
    if (!theme) throw new Error(\`Theme not found: \${id}\`);

    if (!theme.config.extends) return theme;

    const parent = resolveTheme(theme.config.extends, visited);

    // Deep-ish merge: colors/fonts merged shallow, top-level overrides apply.
    const mergedConfig: ThemeConfig = {
        ...parent.config,
        ...theme.config,
        colors: { ...parent.config.colors, ...theme.config.colors },
        fonts: { ...parent.config.fonts, ...theme.config.fonts },
        // Schema: child overrides parent if defined
        schema: theme.config.schema || parent.config.schema,
        // Inherit parent custom CSS appended with child's
        css: [parent.config.css, theme.config.css].filter(Boolean).join("\\n\\n"),
    };

    return {
        config: mergedConfig,
        components: { ...parent.components, ...theme.components },
    };
}

export const themeRegistry: Record<string, Theme> = Object.keys(rawRegistry).reduce(
    (acc, id) => {
        acc[id] = resolveTheme(id);
        return acc;
    },
    {} as Record<string, Theme>
);

export const defaultThemeId = "flat";
`;

    // Ensure output dir exists
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(OUTPUT_FILE, content);
    console.log(`Generated registry for ${themes.length} themes.`);
}

generate().catch(console.error);
